package com.poudel.taskmaster.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

@DynamoDBTable(tableName = "taskmaster")
public class Task {
    private String id;
    private String title;
    private String description;
    private String status;
    private String assignee;
    private String imgURL;
    private ArrayList<History> historyList;

    public Task(){}

    public Task(String title, String description){
        this.title = title;
        this.description = description;
        this.status = "available";
        this.historyList = new ArrayList<>();
    }

    public Task(String title, String description, String assignee){
        this.title = title;
        this.description = description;
        this.status = "assigned";
        this.historyList= new ArrayList<>();
        this.assignee = assignee;
    }


    public History historyCreation(String update) {
        String date = new Date().toString();
        History history = new History(update);
        return history;
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    @DynamoDBAttribute
    public String getTitle() {
        return this.title;
    }

    @DynamoDBAttribute
    public String getDescription() {
        return description;
    }

    @DynamoDBAttribute
    public String getStatus() {
        return status;
    }

    @DynamoDBAttribute
    public String getAssignee() {
        return assignee;
    }

    @DynamoDBAttribute
    public String getImgURL() {
        return imgURL;
    }

    @DynamoDBAttribute
    public ArrayList<History> getHistory() {
        return historyList;
    }

    public void setId(String id) {
        this.id = id;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public void setStatus(String status) {
        this.status= status;
    }

    public void setAssignee(String assignee) {
        this.assignee = assignee;
    }

    public void setImgURL(String imgURL) {
        this.imgURL = imgURL;
    }

    public void setHistory(ArrayList<History> historyList) {
        this.historyList = historyList;
    }

    public void addToHistory(History history){
        this.historyList.add(history);
    }


}
